require("settings")

require("config/lazy")
require("config/colorscheme")
require("config/neotree")
require("config/lualine")
require("config/comment")
require("config/hop")
require("config/autopairs")
require("config/toggleterm")
require("config/bufferline")
require("config/telescope")
require("config/treesitter")
require("config/lsp-zero")
require("config/mason-tool-installer")
require("config/debugging")
require("config/formatter")
require("config/nvim-lint")
require("config/git")
require("config/trouble")
require("config/neodev")

require("after/plugin/autocmd")
require("after/plugin/keymap")
