require("settings")

require("config/lazy")
require("config/colorscheme")
require("config/neotree")
require("config/lualine")
require("config/comment")
require("config/hop")
require("config/autopairs")
require("config/toggleterm")
require("config/bufferline")
require("config/telescope")
require("config/treesitter")
require("config/lsp-zero")
require("config/debugging")

require("after/plugin/autocmd")
require("after/plugin/keymap")
