require("settings")

require("config/lazy")
require("config/colorscheme")

require("config/lsp/lsp-zero")
require("config/lsp/mason-tool-installer")
require("config/lsp/clangd")
require("config/lsp/go")
require("config/lsp/typos")

require("config/neotree")
require("config/lualine")
require("config/comment")
require("config/hop")
require("config/autopairs")
require("config/toggleterm")
require("config/bufferline")
require("config/telescope")
require("config/treesitter")
require("config/debugging")
require("config/formatter")
require("config/nvim-lint")
require("config/git")
require("config/trouble")
require("config/neodev")
require("config/neotest")
require("config/copilot")
require("config/refactoring")
require("config/markdown-preview")
require("config/swagger-preview")

require("after/plugin/autocmd")
require("after/plugin/keymap")
